### ISSUE TITLE
Document the fact that relevant public keys for secret keys from vault have to be imported in client domains

### ISSUE THREAD

**Issue by rysiekpl** [marmarek/qubes-app-linux-split-gpg2#1]
Documentation does not mention the fact that for each secret key handled in the *server/vault* domain, the public key *needs to be imported* into keyring in the *client* domain. This is not clear, and needs to be well-documented.

Original version below:
 -------------------------------------------------

Made an attempt to set `split-gpg2` up in Qubes R4.0. Created a special template (`debian-gpg`, based on Debian 9), installed the built package in it, created two cubes (`vault`, containing the GPG keys; and `mailpile`, which is to be te client).

Created `~user/.split-gpg2-rc`, enabled the service, restarted `mailpile` cube.

Running `gpg2` in `mailpile`:

```
$ gpg2 --list-keys
gpg: directory '/home/user/.gnupg' created
gpg: keybox '/home/user/.gnupg/pubring.kbx' created
gpg: /home/user/.gnupg/trustdb.gpg: trustdb created
```

GnuPG keyring is definitely not empty in `vault`:

```
$ gpg2 --list-keys | wc -l
gpg: Note: signatures using the MD5 algorithm are rejected
3898
```

Not sure how to proceed with debugging. Seems like `gpg2` in `mailpile` isn't even *trying* to use `split-gpg2`. It is definitely installed though:

```
$ dpkg -l | grep split
ii  qubes-gpg-split                      2.0.27-1+deb9u1                   amd64        The Qubes service for secure gpg separation
ii  split-gpg2                           0.1                               all          split-gpg2 for Qubes
```

Perhaps I need to remove `qubes-gpg-split` first? cc @hw42

**Comment by rysiekpl** [comment]
Hmmm. Seems like `split-gpg2-client` service is not running for some reason:

```
$ sudo service split-gpg2-client status
● split-gpg2-client.service - Qubes split-gpg2 client
   Loaded: loaded (/lib/systemd/system/split-gpg2-client.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Mon 2018-02-05 23:28:00 UTC; 11min ago
           └─ ConditionPathExists=/var/run/qubes-service/split-gpg2-client was not met
```

**Comment by rysiekpl** [comment]
Well, even after manually creating the directory (I am guessing that's something that will not fix it, but it was worth a try), service runs but `gpg2` in `mailpile` still does not seem to be trying to talk to `gpg2` in `vault`:

```
user@mailpile:~$ sudo mkdir /var/run/qubes-service/split-gpg2-client
user@mailpile:~$ sudo service split-gpg2-client start
user@mailpile:~$ sudo service split-gpg2-client status
● split-gpg2-client.service - Qubes split-gpg2 client
   Loaded: loaded (/lib/systemd/system/split-gpg2-client.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-02-05 23:42:08 UTC; 2s ago
 Main PID: 1273 (su)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/split-gpg2-client.service
           ‣ 1273 /bin/su - user -c /usr/share/split-gpg2/split-gpg2-client

Feb 05 23:42:08 mailpile systemd[1]: Started Qubes split-gpg2 client.
Feb 05 23:42:08 mailpile su[1273]: Successful su for user by root
Feb 05 23:42:08 mailpile su[1273]: + ??? root:user
Feb 05 23:42:08 mailpile su[1273]: pam_unix(su:session): session opened for user user by (uid=0)
user@mailpile:~$ gpg2 --list-keys
gpg: directory '/home/user/.gnupg' created
gpg: keybox '/home/user/.gnupg/pubring.kbx' created
gpg: /home/user/.gnupg/trustdb.gpg: trustdb created
```

**Comment by marmarek** [comment]
cc @HW42

**Comment by marmarek** [comment]
> ConditionPathExists=/var/run/qubes-service/split-gpg2-client

Use `qvm-service --enable mailpile split-gpg2-client` in dom0.

Note that in split-gpg2 backend qube is used only for _secret_ keys, public keys are handled by client qube.

**Comment by HW42** [comment]
> Note that in split-gpg2 backend qube is used only for secret keys, public keys are handled by client qube.

Exactly. You need to import your public keys in your mail VM.

**Comment by HW42** [comment]
In the backend domain you only have to import your private keys. Then you can try if the frontend can see them with `--list-secret-keys`.

**Comment by rysiekpl** [comment]
> Use qvm-service --enable mailpile split-gpg2-client in dom0.

Yes, that is what I did.

> Note that in split-gpg2 backend qube is used only for secret keys, public keys are handled by client qube.

Right. Well...

```
$ gpg2 --list-secret-keys
$
```

The `mailpile` domain cannot see the keys.

I have had the regular `split-gpg` set-up in these domains, is it possible that they conflict? How can I debug this?

**Comment by rysiekpl** [comment]
FYI, started reimplementing `split-gpg2.rb` in Python3 here: https://github.com/rysiekpl/split-gpg2/blob/master/split-gpg2.py (very early, not at all functional yet)

**Comment by HW42** [comment]
> I have had the regular split-gpg set-up in these domains, is it possible that they conflict?

I don't think so.

> How can I debug this?

 - Double check if you see your keys with `gpg2 --list-secret-keys` in the backend domain.
 - In the frontend domain:
   - `sudo systemctl split-gpg2-clinet`
   - `ss -lxp | grep agent`
   - `ps -ef | grep agent`
 - If the above suggest that the forwarding to the backend seems to work, enable `QUBES_SPLIT_GPG2_DEBUG_LOG` (setting in `.split-gpg2-rc`). Note that the log contains sensitive data, so use test keys/data if you post them unfiltered.

**Comment by HW42** [comment]
I meant to write `sudo systemctl status split-gpg2-client`.

**Comment by HW42** [comment]
> FYI, started reimplementing split-gpg2.rb in Python3 here: https://github.com/rysiekpl/split-gpg2/blob/master/split-gpg2.py (very early, not at all functional yet)

Great! I created a repo (https://github.com/HW42/qubes-app-linux-split-gpg2) under my account so we don't have redirect this via Marek's. I also changed the name to match the convention used for other components.

Please open a PR if you have something (at least somewhat) working.

**Comment by HW42** [comment]
Oh, you might have run into this problem: https://github.com/HW42/qubes-app-linux-split-gpg2/commit/3e27c34a98aef38918d205d4eba688128d93c375

**Comment by rysiekpl** [comment]
Well, commented out the line manually in the service file in the template, halted the template, restarted `vault` and `mailpile` cubes, and got:

```
$ sudo service split-gpg2-client status
● split-gpg2-client.service - Qubes split-gpg2 client
   Loaded: loaded (/lib/systemd/system/split-gpg2-client.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Fri 2018-02-09 22:54:36 UTC; 29s ago
           └─ ConditionPathExists=/var/run/qubes-service/split-gpg2-client was not met
```

**Comment by HW42** [comment]
Are you sure you enabled the `split-gpg2-client` service for your `mailpile` VM?

**Comment by rysiekpl** [comment]
I am sure I have *not* enabled such a service, since the README says to do this:

```
'qvm-service gpg-client-vm enable split-gpg2'
```

Disabling `split-gpg2` now, enabling `split-gpg2-client`, and let's see what happens.

**Comment by HW42** [comment]
Argh, sorry. That's a typo in the README.

**Comment by rysiekpl** [comment]
No worries, happy to be going through stuff and making it more usable to next people who might be interested.

That did the trick, and service is running:

```
$ sudo service split-gpg2-client status
● split-gpg2-client.service - Qubes split-gpg2 client
   Loaded: loaded (/lib/systemd/system/split-gpg2-client.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-02-09 23:06:05 UTC; 5s ago
 Main PID: 507 (su)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/split-gpg2-client.service
           ‣ 507 /bin/su - user -c /usr/share/split-gpg2/split-gpg2-client

Feb 09 23:06:05 mailpile systemd[1]: Started Qubes split-gpg2 client.
Feb 09 23:06:05 mailpile su[507]: Successful su for user by root
Feb 09 23:06:05 mailpile su[507]: + ??? root:user
Feb 09 23:06:05 mailpile su[507]: pam_unix(su:session): session opened for user user by (uid=0)
```

However, it still does not get secret keys from the `vault` domain. Looking around.

**Comment by rysiekpl** [comment]
More debug output (from `mailpile` cube):

```
$ ss -lxp | grep agent
u_dgr  UNCONN     0      0      /run/systemd/cgroups-agent 10519                 * 0                    
u_str  LISTEN     0      5      /run/user/1000/gnupg/S.gpg-agent 18772                 * 0                     users:(("socat",pid=697,fd=5))
u_str  LISTEN     0      5      /var/run/qubes/qrexec-agent 16519                 * 0                    
u_str  LISTEN     0      128    /run/user/1000/gnupg/S.gpg-agent.ssh 17552                 * 0                     users:(("systemd",pid=622,fd=21))
u_str  LISTEN     0      128    /run/user/1000/gnupg/S.gpg-agent.extra 17555                 * 0                     users:(("systemd",pid=622,fd=22))
u_str  LISTEN     0      128    /run/user/1000/gnupg/S.gpg-agent 17557                 * 0                     users:(("systemd",pid=622,fd=23))
u_str  LISTEN     0      128    /run/user/1000/gnupg/S.gpg-agent.browser 17559                 * 0                     users:(("systemd",pid=622,fd=24))
```

And

```
$ ps -ef | grep agent
root       539     1  0 23:06 ?        00:00:00 /usr/lib/qubes/qrexec-agent
user       697   649  0 23:06 ?        00:00:00 socat UNIX-LISTEN:/run/user/1000/gnupg/S.gpg-agent,fork EXEC:/usr/share/split-gpg2/split-gpg2-client-wrapper
user       771   724  0 23:06 ?        00:00:00 /usr/bin/ssh-agent qubes-session
user       955   928  0 23:09 pts/0    00:00:00 grep agent
```

**Comment by HW42** [comment]
This looks fine. Do you see anything in the journal if you try to access your secret keys?

**Comment by rysiekpl** [comment]
Which journal. If you're talking about `journalctl`, you will have to be a bit more specific about arguments, I never took the time to learn the intricacies of `systemd`. ;)

**Comment by rysiekpl** [comment]
Created a completely new cube just for `split-gpg2` testing (eloquently named `split-gpg2-test`), to make sure that having legacy `split-gpg` eunabled previously in `mailpile` cube is not causing problems. Same results (service running, etc, but secret keys still not being received from `vault`).

**Comment by HW42** [comment]
Yeah, I mean `journalctl` (by default there's no syslog running). Use `journalctl -b` for the "syslog" since boot and `journalctl -f` for `tail -f`-style following.

**Comment by rysiekpl** [comment]
Thanks. No, nothing shows up in `journalctl` output when I do `gpg --list-secret-keys` (same for `gpg2 --list-secret-keys` obviously).

**Comment by HW42** [comment]
Then try to enable the split-gpg2 log in the `vault` VM and see if it receives anything.

PS: While fixing the README I noticed two uncommited local changes ;/. Now pushed to my repo.

**Comment by rysiekpl** [comment]
How do I enable split-gpg2 log in the `vault`?

Also, I am starting to think this might be related to some typo in variable names in `~/.split-gpg2-rc`, or the filename of that file itself.

**Comment by HW42** [comment]
With "enable the split-gpg2 log" I mean put something like `export QUBES_SPLIT_GPG2_DEBUG_LOG=/tmp/split-gpg2.log` in `~user/.split-gpg2-rc`.

**Comment by rysiekpl** [comment]
Also also, your repo is not a fork of this repo, is it? This means there is no easy way to merge changes between my fork of this repo, and your repo (apart from doing it manually with `git` in a local cloned copy)...

**Comment by HW42** [comment]
> Also, I am starting to think this might be related to some typo in variable names in `~/.split-gpg2-rc`, or the filename of that file itself.

I rather don't think so. I relatively sure that I used the example as in the git repo recently for a new VM.

**Comment by rysiekpl** [comment]
Ok. Will I need to restart the `vault` cube for the changes in `.split-gpg2-rc` to be put in effect?

**Comment by HW42** [comment]
> Ok. Will I need to restart the `vault` cube for the changes in `.split-gpg2-rc` to be put in effect?

No. Every new connection to the agent will use the new settings (and if you use the command line every `gpg` invocation will be a new connection).

**Comment by rysiekpl** [comment]
Nothing in the log. The logfile doesn't even get created.

**Comment by HW42** [comment]
> Also also, your repo is not a fork of this repo, is it? This means there is no easy way to merge changes between my fork of this repo, and your repo (apart from doing it manually with `git` in a local cloned copy)...

Oh, right, GitHub understands the concept of a fork only if you click in their WebUI ...

Do prefer if I make it a fork of this repo?

**Comment by rysiekpl** [comment]
It would make things a bit easier, but I can survive either way. Your call.

**Comment by rysiekpl** [comment]
Re: debugging -- my feel is we're missing something obvious. Some implicit assumption, perhaps, that I am not aware of.

**Comment by HW42** [comment]
> Nothing in the log. The logfile doesn't even get created.

Ok. So apparently it never connect to the backend domain. Try to run `qrexec-client-vm vault qubes.Gpg2` by hand.

**Comment by rysiekpl** [comment]
Got a question on which cube I want to connect to. Then this:
```
$ qrexec-client-vm vault qubes.Gpg2
OK Pleased to meet you, process 974

```

**Comment by rysiekpl** [comment]
And in logfile in `vault`:

```
$ cat /tmp/split-gpg2.log 
2018-02-09 23:44:15.777327194: 974: connected 
2018-02-09 23:44:15.872834375: 974: A >>> OK Pleased to meet you, process 974
2018-02-09 23:44:15.873041410: 974: C <<< OK Pleased to meet you, process 974
2018-02-09 23:45:03.678694213: 974: disconnected 
```

**Comment by rysiekpl** [comment]
Again, this is R4.0 rc4, there were some Qubes API changes I believe. Perhaps that's the issue?

**Comment by HW42** [comment]
> Got a question on which cube I want to connect to. Then this [...]

Ok, this is how it should work (normally you would white list the access to not always get popups).

Since you never got the popup before for some reason your `gpg` does not connect to the unix socket opened by `socat`

**Comment by HW42** [comment]
What does `gpg --version` say?

**Comment by rysiekpl** [comment]
```
$ gpg --version
gpg (GnuPG) 2.1.18
libgcrypt 1.7.6-beta
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/user/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by rysiekpl** [comment]
Perhaps `gpg2` needs to be explicitly told it needs to be told where the socket is?

This might also be relevant:
```
$ gpgconf --list-dirs
sysconfdir:/etc/gnupg
bindir:/usr/bin
libexecdir:/usr/lib/gnupg
libdir:/usr/lib/x86_64-linux-gnu/gnupg
datadir:/usr/share/gnupg
localedir:/usr/share/locale
socketdir:/run/user/1000/gnupg
dirmngr-socket:/run/user/1000/gnupg/S.dirmngr
agent-ssh-socket:/run/user/1000/gnupg/S.gpg-agent.ssh
agent-extra-socket:/run/user/1000/gnupg/S.gpg-agent.extra
agent-browser-socket:/run/user/1000/gnupg/S.gpg-agent.browser
agent-socket:/run/user/1000/gnupg/S.gpg-agent
homedir:/home/user/.gnupg
$ ls -l /run/user/1000/gnupg/S.gpg-agent
srwxr-xr-x 1 user user 0 Feb  9 23:16 /run/user/1000/gnupg/S.gpg-agent
```

**Comment by HW42** [comment]
No. `split-gpg2` (should) get the path via `gpgconf`.

Try to connect manually to the socket: `socat - unix:/run/user/1000/gnupg/S.gpg-agent`

**Comment by HW42** [comment]
Do you get the popup? And get an entry in the backend log?

**Comment by rysiekpl** [comment]
Hmmm:

```
$ ss -lxp | grep 'gpg-agent '
u_str  LISTEN     0      5      /run/user/1000/gnupg/S.gpg-agent 17205                 * 0                     users:(("socat",pid=721,fd=5))
u_str  LISTEN     0      128    /run/user/1000/gnupg/S.gpg-agent 17517                 * 0                     users:(("systemd",pid=662,fd=22))
```

And:

```
$ ps aux | egrep '(662|721)'
user       662  0.0  0.6  65156  6772 ?        Ss   23:16   0:00 /lib/systemd/systemd --user
user       721  0.0  0.1  24564  1956 ?        S    23:16   0:00 socat UNIX-LISTEN:/run/user/1000/gnupg/S.gpg-agent,fork EXEC:/usr/share/split-gpg2/split-gpg2-client-wrapper
```

Can it be possible that `systemd` somehow "covers" the `socat` socket?

**Comment by rysiekpl** [comment]
> Do you get the popup? And get an entry in the backend log?

Yes:

```
$ socat - unix:/run/user/1000/gnupg/S.gpg-agent
OK Pleased to meet you, process 1017
```

And:

```
2018-02-09 23:57:06.896045955: 1017: connected 
2018-02-09 23:57:06.984800965: 1017: A >>> OK Pleased to meet you, process 1017
2018-02-09 23:57:06.984989136: 1017: C <<< OK Pleased to meet you, process 1017
2018-02-09 23:57:08.989879126: 1017: disconnected 
```

**Comment by rysiekpl** [comment]
Perhaps relevant: both `split-gpg2-test` and `vault` are based on Debian 9.

**Comment by HW42** [comment]
Okay that's how it should be (and also means that the systemd socket isn't a problem). So something is odd with `gpg` (the command line tool).

Try: `strace -f gpg --list-secret-keys 2>&1 | grep 'connect'`

**Comment by rysiekpl** [comment]
Nothing:
```
$ strace -f gpg --list-secret-keys 2>&1 | grep 'connect'
$ 
```

Compared to:
 
```
$ strace -f gpg --list-secret-keys 2>&1 | wc -l
332
```

**Comment by HW42** [comment]
Just to double check: `gpg --list-keys` lists the keys for with `vault` has the secret keys?

**Comment by rysiekpl** [comment]
Oh boy. Adding the relevant public keys in `split-gpg2-test` made it work. README does not mention the fact that public keys for secret keys from `vault` *need* to be already imported in the client domain.

You did say:
> Exactly. You need to import your public keys in your mail VM.

But I understood this to mean "*public keys for people you want to communicate with*", not "*public keys also for your secret keys, otherwise it will not work at all*".

**Comment by rysiekpl** [comment]
I'll take a jab at rewriting the README.md a bit in my fork tomorrow. Thanks for helping me sort it out.

**Comment by HW42** [comment]
> I'll take a jab at rewriting the README.md a bit in my fork tomorrow. Thanks for helping me sort it out.

I added some basic instructions to the README. Feel free to improve and open a PR.

> It would make things a bit easier, but I can survive either way. Your call.

Ok, made a "GitHub fork".

For further issues/PRs please use my repo (till there's an `QubesOS` one).

**Comment by rysiekpl** [comment]
Done: https://github.com/HW42/qubes-app-linux-split-gpg2/pull/1
